<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
		Copyright (C) 2013 - 2014 Peter Varo
		&lt;http://github.com/petervaro/python&gt;

		This program is free software: you can redistribute it
		and/or modify it under the terms of the GNU General
		Public License as published by the Free Software
		Foundation, either version 3 of the License, or (at your
		option) any later version.

		This program is distributed in the hope that it will be
		useful, but WITHOUT ANY WARRANTY; without even the
		implied warranty of MERCHANTABILITY or FITNESS FOR A
		PARTICULAR PURPOSE. See the GNU General Public License
		for more details.

		You should have received a copy of the GNU General Public
		License along with this program, most likely a file in
		the root directory, called "LICENSE". If not, see
		&lt;http://www.gnu.org/licenses&gt;.
	</string>
	<key>fileTypes</key>
	<array>
		<string>pyx</string>
		<string>pxi</string>
		<string>pxd</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bpython[\d.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*((cp?)?def|class)\s+([.\w&gt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Cython</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b[01]+</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x\h+</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0o[0-7]+</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\W|^)\.\d+([eE][+-]?\d+)?[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.floatnumber.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.(\d*([eE][+-]?\d+)?)?[jJ]?(?=\W)</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.pointfloat.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\.\d])\d+[eE][+-]?\d+[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.exponent.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)([1-9]\d*|0)[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.integer_and_complex.decimal.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(global|nonlocal|gil|nogil|extern|api|public|readonly|const(\svolatile)?|inline)\b</string>
			<key>name</key>
			<string>storage.modifier.declaration.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cimport|include|extern|import|from)\b</string>
			<key>name</key>
			<string>keyword.control.import_and_import_from.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(elif|else|except|finally|for|if|try|while|with|break|continue|pass|raise|return|yield|IF|ELIF|ELSE|DEF)\b</string>
			<key>name</key>
			<string>keyword.control.flow_block_delimiters.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|in|is|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.bool.logical.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|assert|by|del)\b</string>
			<key>name</key>
			<string>keyword.other.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|==|&lt;|&gt;|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+=|-=|\*=|/=|//=|%=|&amp;=|\|=|\^=|&lt;&lt;=|&gt;&gt;=|\*\*=</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|-&gt;</string>
			<key>name</key>
			<string>keyword.operator.value_and_annotation_assignment.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\?</string>
			<key>name</key>
			<string>keyword.operator.type_test.cython</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(cdef\s+)?(class)\s+(?=[a-zA-Z_]\w*(\s*\()?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.definition.cython</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\)?\s*:|\s+([\w#\s:]+))</string>
			<key>endCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing_section_begin.cython</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class_entity_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_inheritance</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((cp?)?def)\s+(?=[a-zA-Z_]\w*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\s*:|\n+)</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing_section_begin.cython</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_entity_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_arguments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\)\s*(nogil)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.declaration.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*((-&gt;)|:|\n+)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_annotation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(lambda)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.anonymous.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>:</string>
			<key>name</key>
			<string>meta.function.anonymous.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+</string>
					<key>end</key>
					<string>(?=:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b([a-zA-Z_]\w*)\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.cython</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.cython</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=,|:)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\b[a-zA-Z_]\w*</string>
							<key>name</key>
							<string>variable.parameter.function.cython</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(@\s*[a-zA-Z_]\w*(\.[a-zA-Z_]\w*)*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.decorator.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function.decorator.with_arguments.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(@\s*[a-zA-Z_]\w*(\.[a-zA-Z_]\w*)*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.decorator.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s|$\n?|#)</string>
			<key>name</key>
			<string>meta.function.decorator.without_arguments.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NULL|None|True|False|Ellipsis|NotImplemented|UNAME_SYSNAME|UNAME_NODENAME|UNAME_RELEASE|UNAME_VERSION|UNAME_MACHINE|EXIT_FAILURE|EXIT_SUCCESS|RAND_MAX)\b</string>
			<key>name</key>
			<string>constant.language.word_like.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\W|^)\.\.\.(?=\W|$)</string>
			<key>name</key>
			<string>constant.language.symbol_like.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((c(p|type)?)?def|lambda)\b</string>
			<key>name</key>
			<string>storage.type.function.cython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class)\b</string>
			<key>name</key>
			<string>storage.type.class.cython</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#c_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_exceptions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_function_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_variable_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_continuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language_variables</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.structure.list.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\[|,)\s*(?![\],])</string>
					<key>end</key>
					<string>\s*(?:,|(?=\]))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.structure.dictionary.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;={|,|^)\s*(?![,}])</string>
					<key>end</key>
					<string>\s*(?:(?=\})|(\:))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=:|^)\s*</string>
					<key>end</key>
					<string>\s*(?:(?=\}|,))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=,|;|=|\+|-|\*|/|\||:|&lt;|&gt;|~|%|\^|\\)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.structure.group.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!:|,|;|\[|\{|\}|=|\+|-|\*|/|\||&lt;|&gt;|~|%|\^|\\|\n)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function_call.cython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin_exceptions</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b((Arithmetic|Buffer|Lookup|Assertion|Attribute|EOF|FloatingPoint|Import|Index|Key|Memory|Name|NotImplemented|OS|Overflow|Reference|Runtime|Syntax|Indentation|Tab|System|Type|UnboundLocal|Unicode|Unicode(Encode|Decode|Translate)?|Value|ZeroDivision|Environment|IO|VMS|Windows|BlockingIO|ChildProcess|BrokenPipe|Connection(Aborted|Refused|Reset)?|FileExists|FileNotFound|Interrupted|(Is|Not)ADirectory|Permission|ProcessLookup|Timeout)Error|(User|Deprecation|PendingDeprecation|Syntax|Runtime|Future|Import|Bytes|Resource)Warning|(Base)?Exception|(Generator|System)Exit|KeyboardInterrupt|StopIteration|Warning)\b</string>
			<key>name</key>
			<string>support.type.exception.cython</string>
		</dict>
		<key>builtin_functions</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(__import__|abort|(c|m|re)alloc|(ll?)?abs|all|any|ascii|bin|bsearch|callable|chr|compile|delattr|dir|(ll?)?div|divmod|eval|exec|(_|at)?exit|filter|format|free|getattr|getenv|globals|hasattr|hash|help|hex|id|input|isinstance|issubclass|iter|len|locals|map|max|min|next|oct|ord|pow|print|qsort|range|s?rand|repr|round|setattr|sizeof|sorted|sum|system|vars|zip)\b</string>
			<key>name</key>
			<string>support.function.builtin.cython</string>
		</dict>
		<key>builtin_types</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(basestring|bool|buffer|bytearray|bytes|classmethod|complex|dict|enumerate|file|frozenset|list|memoryview|object|open|property|reversed|set|slice|staticmethod|str|super|tuple|type)\b</string>
			<key>name</key>
			<string>support.type.cython</string>
		</dict>
		<key>c_types</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(bint|(long\s)?double|enum|float|struct|union|void|const|fused|((un)?signed\s)?(char|((short|long(\slong)?)\s)?int|short|long(\slong)?))\b</string>
			<key>name</key>
			<string>support.type.c_types.cython</string>
		</dict>
		<key>class_entity_name</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z_]\w*)</string>
			<key>contentName</key>
			<string>entity.name.type.class.cython</string>
			<key>end</key>
			<string>(?!\w)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_class</string>
				</dict>
			</array>
		</dict>
		<key>class_inheritance</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>contentName</key>
			<string>meta.class.inheritance.cython</string>
			<key>end</key>
			<string>\)|:</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\(|,)\s*</string>
					<key>contentName</key>
					<string>entity.other.inherited-class.cython</string>
					<key>end</key>
					<string>\s*(?:,|(?=\)))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.inheritance.cython</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.hashmark.cython</string>
		</dict>
		<key>constant_placeholder</key>
		<dict>
			<key>match</key>
			<string>%(\(\w+\))?#?0?-?[ ]?\+?(\d*|\*)(\.(\d*|\*))?[hlL]?[diouxXeEfFgGcrs%]</string>
			<key>name</key>
			<string>string.interpolated.placeholder.cython</string>
		</dict>
		<key>entity_name_class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#illegal_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>entity_name_function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#magic_function_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>escaped_characters</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|[0-7]{3}|\n|\"|\'|a|b|f|n|r|t|v|\\)</string>
			<key>name</key>
			<string>constant.character.escaped.special.cython</string>
		</dict>
		<key>escaped_unicode_characters</key>
		<dict>
			<key>match</key>
			<string>\\(u\h{4}|U\h{8}|N\{[a-zA-Z\s]+\})</string>
			<key>name</key>
			<string>constant.character.escaped.cython</string>
		</dict>
		<key>format_mini_language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{\}</string>
					<key>name</key>
					<string>constant.other.placeholder.format.cython</string>
				</dict>
			</array>
		</dict>
		<key>function_annotation</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\))\s*(-&gt;)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.annotation.assignment.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s*:)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>function_arguments</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([a-zA-Z_]\w*)\s*(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.cython</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|[\n)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=(=))\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.cython</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=,|[\n)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=:)\s*</string>
							<key>end</key>
							<string>(?=,|(=)|[\n)])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.cython</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([a-zA-Z_]\w*)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|[\n)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=:)\s*</string>
							<key>end</key>
							<string>(?=,|[\n)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function_entity_name</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z_]\w*)</string>
			<key>contentName</key>
			<string>entity.name.function.cython</string>
			<key>end</key>
			<string>(?!\w)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_function</string>
				</dict>
			</array>
		</dict>
		<key>generic_names</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_]\w*</string>
		</dict>
		<key>illegal_names</key>
		<dict>
			<key>match</key>
			<string>\b(and|api|as|assert|break|by|class|continue|(c(p|type)?)?def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|public|raise|return|try|while|with|yield)\b</string>
			<key>name</key>
			<string>invalid.illegal_names.name.cython</string>
		</dict>
		<key>keyword_arguments</key>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z_]\w*)\s*(=)(?!=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.cython</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.cython</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=,|[\n)])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>language_variables</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(self|cls)\b</string>
			<key>name</key>
			<string>variable.language.cython</string>
		</dict>
		<key>line_continuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.line.cython</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unexpected_text.cython</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)(.*)$\n?</string>
		</dict>
		<key>magic_function_names</key>
		<dict>
			<key>match</key>
			<string>\b__(abs|add|and|bool|bytes|call|ceil|complex|contains|copy|dealloc|deepcopy|del|delattr|delete|delitem|dir|div|divmod|enter|eq|exit|float|floor|floordiv|format|ge|get|getattr|getattribute|getinitargs|getitem|getnewargs|getstate|gt|hash|hex|iadd|iand|idiv|ifloordiv|ilshift|imul|index|c?init|instancecheck|int|invert|ior|ipow|irshift|isub|iter|itruediv|ixor|le|len|lshift|lt|metaclass|missing|mod|mul|ne|neg|new|next|oct|or|pos|pow|prepare|radd|rand|rdiv|rdivmod|reduce|reduce_ex|repr|reversed|rfloordiv|rlshift|rmod|rmul|ror|round|rpow|rrshift|rshift|rsub|rtruediv|rxor|set|setattr|setitem|setstate|signatures|str|sub|subclasscheck|subclasshook|truediv|trunc|unicode|weakref|xor)__\b</string>
			<key>name</key>
			<string>support.function.magic.cython</string>
		</dict>
		<key>magic_variable_names</key>
		<dict>
			<key>match</key>
			<string>\b__(all|annotations|bases|builtins|class|debug|dict|doc|file|members|metaclass|mro|name|qualname|slots|weakref)__\b</string>
			<key>name</key>
			<string>support.variable.magic.cython</string>
		</dict>
		<key>regular_expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\()\?(=|!|&lt;=|&lt;!|:|P&lt;[a-z]\w*?&gt;|\(([1-9]\d?|[a-zA-Z_]\w*)\))</string>
					<key>name</key>
					<string>constant.character.escape.cython</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.cython</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\((\?P=)([a-zA-Z_]\w*)\)</string>
					<key>name</key>
					<string>keyword.other.group_reference_name.regex.cython</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[bBAZzG]|\^|\$</string>
					<key>name</key>
					<string>keyword.control.anchor.regex.cython</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[1-9]\d?</string>
					<key>name</key>
					<string>keyword.other.group_reference_order.regex.cython</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[?+*][?+]?|\{(\d+,\d+|\d+,|,\d+|\d+)\}\??</string>
					<key>name</key>
					<string>keyword.operator.quantifier.regex.cython</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.or.regex.cython</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(\?#</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>comment.block.regex.cython</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(\?[aiLmsux]+\)</string>
					<key>name</key>
					<string>keyword.other.option_toggle.regex.cython</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regular_expressions_escaped_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regular_expressions_character_classes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[()]</string>
					<key>name</key>
					<string>keyword.operator.group.regex.cython</string>
				</dict>
			</array>
		</dict>
		<key>regular_expressions_character_classes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[wWsSdD]|\.</string>
					<key>name</key>
					<string>constant.character.character_class.regex.cython</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[(\^)?(\](?=.*\]))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.negation.regex.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>constant.other.character_class.set.regex.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\[|\\\\|\\\]</string>
							<key>name</key>
							<string>constant.character.escaped.special.regex.except.cython</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions_character_classes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions_escaped_characters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>regular_expressions_escaped_characters</key>
		<dict>
			<key>match</key>
			<string>\\(\\|\?|\.|\*|\+|\{|\}|\||\(|\)|\[|\]|\^|\$)</string>
			<key>name</key>
			<string>constant.character.escaped.special.regex.cython</string>
		</dict>
		<key>string_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_unicode_characters</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.cython</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.cython</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.cython</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.cython</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.cython</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.cython</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cython</string>
	<key>uuid</key>
	<string>D085155B-E40A-40B3-8FEC-6865318CDEEA</string>
</dict>
</plist>
