<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
		Written by Peter Varo (c)2013
		http://github.com/petervaro/python3
	</string>
	<key>fileTypes</key>
	<array>
		<string>py</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bpython[\d.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class)\s+([.\w&gt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>name</key>
	<string>PythonLang 3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.hashmark.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x\h+</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0o[0-7]+</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\W|^)\.\d+([eE][+-]?\d+)?[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.floatnumber.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.(\d+([eE][+-]?\d+)?)?[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.pointfloat.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\.\d])\d+[eE][+-]?\d+[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.exponent.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)([1-9]\d*|0)[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.integer_and_complex.decimal.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(global|nonlocal)\b</string>
			<key>name</key>
			<string>storage.modifier.declaration.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|from)\b</string>
			<key>name</key>
			<string>keyword.control.import_and_import_from.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(elif|else|except|finally|for|if|try|while|with|break|continue|pass|raise|return|yield)\b</string>
			<key>name</key>
			<string>keyword.control.flow_block_delimiters.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|in|is|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.bool.logical.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|assert|del)\b</string>
			<key>name</key>
			<string>keyword.other.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|==|&lt;|&gt;|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+=|-=|\*=|/=|//=|%=|&amp;=|\|=|\^=|&lt;&lt;=|&gt;&gt;=|\*\*=</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|-&gt;</string>
			<key>name</key>
			<string>keyword.operator.assignment.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(None|True|False|Ellipsis|NotImplemented)\b</string>
			<key>name</key>
			<string>constant.language.python</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin_exceptions</key>
		<dict>
			<key>match</key>
			<string>(?x)\b((Arithmetic|Buffer|Lookup|Assertion|Attribute|EOF|FloatingPoint|Import|Index|Key|Memory|Name|NotImplemented|OS|Overflow|Reference|Runtime|Syntax|Indentation|Tab|System|Type|UnboundLocal|Unicode|Unicode(Encode|Decode|Translate)?|Value|ZeroDivision|Environment|IO|VMS|Windows|BlockingIO|ChildProcess|BrokenPipe|Connection(Aborted|Refused|Reset)?|FileExists|FileNotFound|Interrupted|(Is|Not)ADirectory|Permission|ProcessLookup|Timeout)Error|(User|Deprecation|PendingDeprecation|Syntax|Runtime|Future|Import|Bytes|Resource)Warning|(Base)?Exception|(Generator|System)Exit|KeyboardInterrupt|StopIteration|Warning)\b</string>
			<key>name</key>
			<string>support.type.exception.python</string>
		</dict>
		<key>builtin_functions</key>
		<dict>
			<key>match</key>
			<string>(?x)\b(__import__|abs|all|any|ascii|bin|callable|chr|compile|delattr|dir|divmod|eval|exec|filter|format|getattr|globals|hasattr|hash|help|hex|id|input|isinstance|issubclass|iter|len|locals|map|max|min|next|oct|ord|pow|print|range|repr|round|setattr|sorted|sum|vars|zip)\b</string>
			<key>name</key>
			<string>support.function.builtin.python</string>
		</dict>
		<key>builtin_types</key>
		<dict>
			<key>match</key>
			<string>(?x)\b(basestring|bool|buffer|bytearray|bytes|classmethod|complex|dict|enumerate|file|float|frozenset|int|list|memoryview|object|open|property|reversed|set|slice|staticmethod|str|super|tuple|type)\b</string>
			<key>name</key>
			<string>support.type.python</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.python</string>
	<key>uuid</key>
	<string>851b1429-b8b4-4c1e-8030-399bda994393</string>
</dict>
</plist>
