<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
		Copyright (C) 2013 - 2014 Peter Varo
		&lt;http://github.com/petervaro/python&gt;

		This program is free software: you can redistribute it
		and/or modify it under the terms of the GNU General
		Public License as published by the Free Software
		Foundation, either version 3 of the License, or (at your
		option) any later version.

		This program is distributed in the hope that it will be
		useful, but WITHOUT ANY WARRANTY; without even the
		implied warranty of MERCHANTABILITY or FITNESS FOR A
		PARTICULAR PURPOSE. See the GNU General Public License
		for more details.

		You should have received a copy of the GNU General Public
		License along with this program, most likely a file in
		the root directory, called "LICENSE". If not, see
		&lt;http://www.gnu.org/licenses&gt;.
	</string>
	<key>fileTypes</key>
	<array>
		<string>py</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bpython[\d.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class)\s+([.\w&gt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Python3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b[01]+</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x\h+</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0o[0-7]+</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\W|^)\.\d+([eE][+-]?\d+)?[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.floatnumber.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.(\d*([eE][+-]?\d+)?)?[jJ]?(?=\W)</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.pointfloat.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\.\d])\d+[eE][+-]?\d+[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.float_and_complex.decimal.exponent.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!\.)([1-9]\d*|0)[jJ]?</string>
			<key>name</key>
			<string>constant.numeric.integer_and_complex.decimal.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(global|nonlocal)\b</string>
			<key>name</key>
			<string>storage.modifier.declaration.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|from)\b</string>
			<key>name</key>
			<string>keyword.control.import_and_import_from.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(elif|else|except|finally|for|if|try|while|with|break|continue|pass|raise|return|yield)\b</string>
			<key>name</key>
			<string>keyword.control.flow_block_delimiters.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|in|is|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.bool.logical.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|assert|del)\b</string>
			<key>name</key>
			<string>keyword.other.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|==|&lt;|&gt;|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+=|-=|\*=|/=|//=|%=|&amp;=|\|=|\^=|&lt;&lt;=|&gt;&gt;=|\*\*=</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|-&gt;</string>
			<key>name</key>
			<string>keyword.operator.value_and_annotation_assignment.python.3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(class)\s+(?=[a-zA-Z_]\w*(\s*\()?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\)?\s*:|\s+([\w#\s:]+))</string>
			<key>endCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing_section_begin.python.3</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class_entity_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_inheritance</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(def)\s+(?=[a-zA-Z_]\w*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\s*:)</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing_section_begin.python.3</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_entity_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_annotation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(lambda)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.anonymous.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>:</string>
			<key>name</key>
			<string>meta.function.anonymous.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+</string>
					<key>end</key>
					<string>(?=:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b([a-zA-Z_]\w*)\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.python.3</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.python.3</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=,|:)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\b[a-zA-Z_]\w*</string>
							<key>name</key>
							<string>variable.parameter.function.python.3</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(@\s*[a-zA-Z_]\w*(\.[a-zA-Z_]\w*)*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.decorator.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function.decorator.with_arguments.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(@\s*[a-zA-Z_]\w*(\.[a-zA-Z_]\w*)*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.decorator.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s|$\n?|#)</string>
			<key>name</key>
			<string>meta.function.decorator.without_arguments.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(None|True|False|Ellipsis|NotImplemented)\b</string>
			<key>name</key>
			<string>constant.language.word_like.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\W|^)\.\.\.(?=\W|$)</string>
			<key>name</key>
			<string>constant.language.symbol_like.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def|lambda)\b</string>
			<key>name</key>
			<string>storage.type.function.python.3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class)\b</string>
			<key>name</key>
			<string>storage.type.class.python.3</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtin_exceptions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_function_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#magic_variable_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_continuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language_variables</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.structure.list.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\[|,)\s*(?![\],])</string>
					<key>end</key>
					<string>\s*(?:,|(?=\]))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.structure.dictionary.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\{|,|^)\s*(?![,}])</string>
					<key>end</key>
					<string>\s*(?:(?=\})|:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=:|^)\s*</string>
					<key>end</key>
					<string>\s*(?:(?=\})|,)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=,|;|=|\+|-|\*|/|\||:|&lt;|&gt;|~|%|\^|\\)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.structure.group.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!:|,|;|\[|\{|\}|=|\+|-|\*|/|\||&lt;|&gt;|~|%|\^|\\|\n)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function_call.python.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin_exceptions</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b((Arithmetic|Buffer|Lookup|Assertion|Attribute|EOF|FloatingPoint|Import|Index|Key|Memory|Name|NotImplemented|OS|Overflow|Reference|Runtime|Syntax|Indentation|Tab|System|Type|UnboundLocal|Unicode|Unicode(Encode|Decode|Translate)?|Value|ZeroDivision|Environment|IO|VMS|Windows|BlockingIO|ChildProcess|BrokenPipe|Connection(Aborted|Refused|Reset)?|FileExists|FileNotFound|Interrupted|(Is|Not)ADirectory|Permission|ProcessLookup|Timeout)Error|(User|Deprecation|PendingDeprecation|Syntax|Runtime|Future|Import|Bytes|Resource)Warning|(Base)?Exception|(Generator|System)Exit|KeyboardInterrupt|StopIteration|Warning)\b</string>
			<key>name</key>
			<string>support.type.exception.python.3</string>
		</dict>
		<key>builtin_functions</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(__import__|abs|all|any|ascii|bin|callable|chr|compile|delattr|dir|divmod|eval|exec|filter|format|getattr|globals|hasattr|hash|help|hex|id|input|isinstance|issubclass|iter|len|locals|map|max|min|next|oct|ord|pow|print|range|repr|round|setattr|sorted|sum|vars|zip)\b</string>
			<key>name</key>
			<string>support.function.builtin.python.3</string>
		</dict>
		<key>builtin_types</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(basestring|bool|bytearray|bytes|classmethod|complex|dict|enumerate|float|frozenset|int|list|memoryview|object|open|property|reversed|set|slice|staticmethod|str|super|tuple|type)\b</string>
			<key>name</key>
			<string>support.type.python.3</string>
		</dict>
		<key>class_entity_name</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z_]\w*)</string>
			<key>contentName</key>
			<string>entity.name.type.class.python.3</string>
			<key>end</key>
			<string>(?!\w)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_class</string>
				</dict>
			</array>
		</dict>
		<key>class_inheritance</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>contentName</key>
			<string>meta.class.inheritance.python.3</string>
			<key>end</key>
			<string>\)|:</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\(|,)\s*</string>
					<key>contentName</key>
					<string>entity.other.inherited-class.python.3</string>
					<key>end</key>
					<string>\s*(?:,|(?=\)))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.inheritance.python.3</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.hashmark.python.3</string>
		</dict>
		<key>constant_placeholder</key>
		<dict>
			<key>match</key>
			<string>%(\(\w+\))?#?0?-?[ ]?\+?(\d*|\*)(\.(\d*|\*))?[hlL]?[diouxXeEfFgGcrs%]</string>
			<key>name</key>
			<string>string.interpolated.placeholder.python.3</string>
		</dict>
		<key>entity_name_class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#illegal_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>entity_name_function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#magic_function_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic_names</string>
				</dict>
			</array>
		</dict>
		<key>escaped_characters</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|[0-7]{3}|\n|\"|\'|a|b|f|n|r|t|v|\\)</string>
			<key>name</key>
			<string>constant.character.escaped.special.python.3</string>
		</dict>
		<key>escaped_unicode_characters</key>
		<dict>
			<key>match</key>
			<string>\\(u\h{4}|U\h{8}|N\{[a-zA-Z\s]+\})</string>
			<key>name</key>
			<string>constant.character.escaped.python.3</string>
		</dict>
		<key>format_mini_language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{\}</string>
					<key>name</key>
					<string>constant.other.placeholder.format.python.3</string>
				</dict>
			</array>
		</dict>
		<key>function_annotation</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\))\s*(-&gt;)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.annotation.assignment.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s*:)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>function_arguments</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>(?=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([a-zA-Z_]\w*)\s*(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.python.3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|[\n)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=(=))\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.python.3</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=,|[\n)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=:)\s*</string>
							<key>end</key>
							<string>(?=,|(=)|[\n)])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.python.3</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([a-zA-Z_]\w*)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=,|[\n)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=:)\s*</string>
							<key>end</key>
							<string>(?=,|[\n)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function_entity_name</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z_]\w*)</string>
			<key>contentName</key>
			<string>entity.name.function.python.3</string>
			<key>end</key>
			<string>(?!\w)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_function</string>
				</dict>
			</array>
		</dict>
		<key>generic_names</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_]\w*</string>
		</dict>
		<key>illegal_names</key>
		<dict>
			<key>match</key>
			<string>\b(and|as|assert|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|raise|return|try|while|with|yield)\b</string>
			<key>name</key>
			<string>invalid.illegal_names.name.python.3</string>
		</dict>
		<key>keyword_arguments</key>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z_]\w*)\s*(=)(?!=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.python.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.python.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=,|[\n)])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>language_variables</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(self|cls)\b</string>
			<key>name</key>
			<string>variable.language.python.3</string>
		</dict>
		<key>line_continuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.line.python.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unexpected_text.python.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)(.*)$\n?</string>
		</dict>
		<key>magic_function_names</key>
		<dict>
			<key>match</key>
			<string>\b__(abs|add|and|bool|bytes|call|ceil|complex|contains|copy|deepcopy|del|delattr|delete|delitem|dir|div|divmod|enter|eq|exit|float|floor|floordiv|format|ge|get|getattr|getattribute|getinitargs|getitem|getnewargs|getstate|gt|hash|hex|iadd|iand|idiv|ifloordiv|ilshift|imul|index|init|instancecheck|int|invert|ior|ipow|irshift|isub|iter|itruediv|ixor|le|len|lshift|lt|metaclass|missing|mod|mul|ne|neg|new|next|oct|or|pos|pow|prepare|radd|rand|rdiv|rdivmod|reduce|reduce_ex|repr|reversed|rfloordiv|rlshift|rmod|rmul|ror|round|rpow|rrshift|rshift|rsub|rtruediv|rxor|set|setattr|setitem|setstate|sizeof|str|sub|subclasscheck|subclasshook|truediv|trunc|unicode|weakref|xor)__\b</string>
			<key>name</key>
			<string>support.function.magic.python.3</string>
		</dict>
		<key>magic_variable_names</key>
		<dict>
			<key>match</key>
			<string>\b__(all|annotations|bases|builtins|class|debug|dict|doc|file|members|metaclass|mro|name|qualname|slots|weakref)__\b</string>
			<key>name</key>
			<string>support.variable.magic.python.3</string>
		</dict>
		<key>regular_expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\()\?(=|!|&lt;=|&lt;!|:|P&lt;[a-zA-Z_]\w*?&gt;|\(([1-9]\d?|[a-zA-Z_]\w*)\))</string>
					<key>name</key>
					<string>constant.character.escape.python.3</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.python.3</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\((\?P=)([a-zA-Z_]\w*)\)</string>
					<key>name</key>
					<string>keyword.other.group_reference_name.regex.python.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[bBAZzG]|\^|\$</string>
					<key>name</key>
					<string>keyword.control.anchor.regex.python.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[1-9]\d?</string>
					<key>name</key>
					<string>keyword.other.group_reference_order.regex.python.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[?+*][?+]?|\{(\d+,\d+|\d+,|,\d+|\d+)\}\??</string>
					<key>name</key>
					<string>keyword.operator.quantifier.regex.python.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.or.regex.python.3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(\?#</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>comment.block.regex.python.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(\?[aiLmsux]+\)</string>
					<key>name</key>
					<string>keyword.other.option_toggle.regex.python.3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regular_expressions_escaped_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regular_expressions_character_classes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[()]</string>
					<key>name</key>
					<string>keyword.operator.group.regex.python.3</string>
				</dict>
			</array>
		</dict>
		<key>regular_expressions_character_classes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[wWsSdD]|\.</string>
					<key>name</key>
					<string>constant.character.character_class.regex.python.3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[(\^)?(\](?=.*\]))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.negation.regex.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>constant.other.character_class.set.regex.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\[|\\\\|\\\]</string>
							<key>name</key>
							<string>constant.character.escaped.special.regex.except.python.3</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions_character_classes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions_escaped_characters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>regular_expressions_escaped_characters</key>
		<dict>
			<key>match</key>
			<string>\\(\\|\?|\.|\*|\+|\{|\}|\||\(|\)|\[|\]|\^|\$)</string>
			<key>name</key>
			<string>constant.character.escaped.special.regex.python.3</string>
		</dict>
		<key>string_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_unicode_characters</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'''</string>
					<key>name</key>
					<string>string.quoted.single.block.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.python.3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.python.3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.line.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""</string>
					<key>name</key>
					<string>string.quoted.double.block.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([bBuU]?)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.python.3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([rR][bB]|[bB][rR]|[rR])"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.python.3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed_string.python.3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.line.python.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#regular_expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.python.3</string>
	<key>uuid</key>
	<string>851B1429-B8B4-4C1E-8030-399BDA994393</string>
</dict>
</plist>
